UPDATE core_config_data SET value = 'http://10.10.48.25:44380' WHERE path in ('erpconnector/general/api_url');
UPDATE core_config_data SET value = 'de0b31477281cd177e5a6a55a3c18c4a' WHERE path in ('pimconnector/general/api_key');
UPDATE core_config_data SET value = 'https://31.179.196.76/pimcore-graphql-webservices' WHERE path in ('pimconnector/general/api_url');
UPDATE core_config_data SET value = 'mailhog' WHERE path in ('smtp/configuration_option/host');
UPDATE core_config_data SET value = 'smtp' WHERE path in ('smtp/configuration_option/authentication');
UPDATE core_config_data SET value = '1025' WHERE path in ('smtp/configuration_option/port');
UPDATE core_config_data SET value = 'elasticsearch' WHERE path in ('catalog/search/elasticsearch7_server_hostname');
UPDATE core_config_data SET value = 'd0:3:fh6IdRUbiaWA+7lxmg8JecfEndtJlDfA37xFlCvmL+Fmqwa1+xaalU3be7sKqokO+L/Bsnurlm7OhmAutAfRO7aqWIA=' WHERE path in ('recaptcha_frontend/type_recaptcha_v3/public_key');
UPDATE core_config_data SET value = '0:3:GGCMppOoE61s7rv5rf+9Mwgap8Tm7cHT0jo+ruNKkgp3VsVJSk2hZD+BauwRMYNFW5pbxOQgv8Qk0f4rjrGRmahEZCI=' WHERE path in ('recaptcha_frontend/type_recaptcha_v3/private_key');
UPDATE core_config_data SET value = 'https://nginx.helikon-tex.orb.local/' WHERE path in ('web/unsecure/base_url', 'web/secure/base_url', 'web/unsecure/base_link_url', 'web/secure/base_link_url') AND scope_id = 0;
UPDATE core_config_data SET value = 'https://nginx.helikon-tex.orb.local/' WHERE path in ('web/unsecure/base_url', 'web/secure/base_url', 'web/unsecure/base_link_url', 'web/secure/base_link_url') AND scope_id = 2;
UPDATE core_config_data SET value = 'https://nginx.helikon-tex.orb.local/en/' WHERE path in ('web/unsecure/base_url', 'web/secure/base_url', 'web/unsecure/base_link_url', 'web/secure/base_link_url') AND scope_id = 1;
UPDATE core_config_data SET value = 'https://nginx.helikon-tex.orb.local/pl/' WHERE path in ('web/unsecure/base_url', 'web/secure/base_url', 'web/unsecure/base_link_url', 'web/secure/base_link_url') AND scope_id = 3;
UPDATE core_config_data SET value = 'https://nginx.helikon-tex.orb.local/static/' WHERE path in ('web/unsecure/base_static_url', 'web/secure/base_static_url');
UPDATE core_config_data SET value = 'https://nginx.helikon-tex.orb.local/media/' WHERE path in ('web/unsecure/base_media_url', 'web/secure/base_media_url');
